### ISSUE TITLE
Working?

### ISSUE THREAD

**Issue by Phlegethon90** [Perry-Olsson/gradle-hot-reload#1]
Hi! Do you have the solution for your problem? I saw your post on stackoverflow and I have the same problem...

**Comment by Perry-Olsson** [comment]
@Phlegethon90 Hey sorry for the delay, yeah actually we were eventually able to get it working via a bit of a class path hack. Here's a snippet of our build.gradle.kts file in the module that has our spring code:
```
tasks {
  bootRun {
    val moduleNames = rootProject.childProjects.map {
      it.key
    }
    classpath = files(sourceSets.getByName("main").output.classesDirs) +
      files(
                sourceSets.getByName("main").runtimeClasspath.filter { file ->
                  moduleNames.none {
                    file.name.contains(it)
                  }
               }
             )
    val moduleClasspaths = rootProject.childProjects.map {
      "${it.value.buildDir}/classes/kotlin/main"
    }
    moduleClasspaths.foreach {
      classpath(it)
    }
  }
}
```

**Comment by Phlegethon90** [comment]
Hey! No problem! Thank you very much for answering! I got it working, too, after reading the documentation (again) multiple times. 😄 Maybe you like it and can use it yourself:

The library to be included must have an outgoing variant with `org.gradle.libraryelements` set to `classes` (typically provided by the plugin `java-library` automatically). In the consuming (Spring Boot) project you have to declare, that the resolving configuration, which you need, must use this variant:

```kotlin
configurations {
    runtimeClasspath { // or another configuration which needs classes
        attributes {
            attribute(
                LibraryElements.LIBRARY_ELEMENTS_ATTRIBUTE,
                objects.named(LibraryElements.CLASSES),
            )
        }
    }
}
```
